version: '2'
services:
  server:
    build: .
    ports:
     - "8888:8888"
    depends_on:
     - redis
     - db
     - queue
    environment:
     - POSTGRES_ADDRESS=192.168.99.100
     - REDIS_ADDRESS=192.168.99.100
     - RABBITMQ_ADDRESS=192.168.99.100
     - SERVER_PORT=8888
     - ddl=create-drop
  redis:
    image: redis
    ports:
     - "6379:6379"
  queue:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE='ABCDABCD'
      - RABBITMQ_DEFAULT_USER=hpemc
      - RABBITMQ_DEFAULT_PASS=password
    ports:
     - "5672:5672"
     - "15672:15672"
  db:
    image: postgres
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER=hpemc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hpemc

